const modal=document.getElementById("tool-modal"), form=document.getElementById("tool-form"), result=document.getElementById("tool-result"), title=document.getElementById("modal-title"), copy=document.getElementById("modal-copy");
document.getElementById("year").textContent=new Date().getFullYear();
const configs={
 keywords:{title:"Keyword Research",copy:"Enter a seed keyword to create a starter list of related query patterns.",html:'<div class="form-row"><input class="input" id="tool-input" placeholder="e.g. seo tools"><button class="primary-small" id="run-tool">Research</button></div>'},
 youtube:{title:"YouTube SEO Planner",copy:"Create a starter optimization checklist for a video topic.",html:'<div class="form-row"><input class="input" id="tool-input" placeholder="e.g. YouTube SEO"><button class="primary-small" id="run-tool">Plan</button></div>'},
 audit:{title:"Website SEO Audit",copy:"Paste a URL to prepare a basic client-side SEO checklist. This initial version does not fetch external pages.",html:'<div class="form-row"><input class="input" id="tool-input" placeholder="https://example.com"><button class="primary-small" id="run-tool">Check</button></div>'},
 meta:{title:"Meta Tag Generator",copy:"Generate starter title and description tags from your page topic.",html:'<div class="form-row"><input class="input" id="tool-input" placeholder="Page topic"><button class="primary-small" id="run-tool">Generate</button></div>'},
 density:{title:"Keyword Density",copy:"Paste text and a target keyword to calculate approximate keyword density.",html:'<textarea class="input" id="tool-text" rows="7" placeholder="Paste your content here..."></textarea><div class="form-row"><input class="input" id="tool-input" placeholder="Target keyword"><button class="primary-small" id="run-tool">Analyze</button></div>'},
 sitemap:{title:"Sitemap Helper",copy:"Enter your homepage URL to generate a minimal XML sitemap.",html:'<div class="form-row"><input class="input" id="tool-input" value="https://rankpilot.eu.cc/"><button class="primary-small" id="run-tool">Generate</button></div>'}
};
function openTool(key){const c=configs[key];if(!c)return;title.textContent=c.title;copy.textContent=c.copy;form.innerHTML=c.html;result.hidden=true;result.innerHTML="";modal.classList.add("open");modal.setAttribute("aria-hidden","false");const btn=document.getElementById("run-tool");if(btn)btn.onclick=()=>runTool(key)}
function runTool(key){const input=document.getElementById("tool-input")?.value.trim();const textInput=document.getElementById("tool-text")?.value||"";if(!input&&key!=="density"){result.hidden=false;result.innerHTML="<p class='warn'>Please enter a value first.</p>";return}
let html="";
if(key==="keywords"){const base=input.toLowerCase();const ideas=[base+" guide", "best "+base, base+" tools", base+" for beginners", base+" checklist", base+" tips", "how to use "+base, base+" strategy"];html='<h4>Starter keyword ideas</h4><ul class="check-list">'+ideas.map(x=>"<li>"+x+"</li>").join("")+"</ul><p class="good">Tip: validate volume, competition, and search intent before targeting a keyword.</p>'}
if(key==="youtube"){html='<h4>Optimization checklist</h4><ul class="check-list"><li class="good">Put the primary topic naturally in the title.</li><li class="good">Explain the video value early in the description.</li><li class="good">Use closely related phrases instead of keyword stuffing.</li><li class="good">Match the thumbnail promise to the actual video.</li></ul>'}
if(key==="audit"){html='<h4>Basic checks</h4><ul class="check-list"><li>✓ HTTPS URL format</li><li>✓ Descriptive page title</li><li>✓ Unique meta description</li><li>✓ One clear H1</li><li>✓ Mobile-friendly layout</li><li>✓ Internal links to important pages</li></ul><p class="warn">A full crawl requires a server-side fetch/crawler and will be added in a later version.</p>'}
if(key==="meta"){const topic=input.replace(/[<>]/g,"");html='<h4>Starter tags</h4><pre>&lt;title&gt;'+topic+' | RankPilot&lt;/title&gt;\n&lt;meta name="description" content="Learn about '+topic+' with practical tips, tools, and resources."&gt;</pre><p class="good">Review the wording and keep it accurate to the page.</p>'}
if(key==="density"){const kw=input.toLowerCase();if(!kw){result.hidden=false;result.innerHTML="<p class='warn'>Enter a target keyword.</p>";return}const words=textInput.toLowerCase().match(/[a-z0-9]+(?:'[a-z0-9]+)*/g)||[];const target=kw.match(/[a-z0-9]+(?:'[a-z0-9]+)*/g)||[];let count=0;for(let i=0;i<=words.length-target.length;i++){if(target.every((w,j)=>words[i+j]===w))count++}const density=words.length?((count*target.length/words.length)*100).toFixed(2):"0.00";html='<h4>Result</h4><p><strong>'+words.length+'</strong> words · <strong>'+count+'</strong> exact phrase occurrences · approximate density <strong>'+density+'%</strong></p>'}
if(key==="sitemap"){const u=input.replace(/\/$/,"");html='<h4>XML sitemap</h4><pre>&lt;?xml version="1.0" encoding="UTF-8"?&gt;\n&lt;urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"&gt;\n  &lt;url&gt;\n    &lt;loc&gt;'+u+'/&lt;/loc&gt;\n  &lt;/url&gt;\n&lt;/urlset&gt;</pre>'}
result.hidden=false;result.innerHTML=html}
document.querySelectorAll("[data-tool]").forEach(b=>b.addEventListener("click",()=>openTool(b.dataset.tool)));
document.querySelector(".modal-close").onclick=()=>modal.classList.remove("open");document.querySelector(".modal-backdrop").onclick=()=>modal.classList.remove("open");
document.querySelector(".menu-toggle").onclick=()=>{const n=document.querySelector(".nav");n.classList.toggle("open");document.querySelector(".menu-toggle").setAttribute("aria-expanded",n.classList.contains("open"))};
document.querySelectorAll(".nav a").forEach(a=>a.onclick=()=>document.querySelector(".nav").classList.remove("open"));